services:
  - type: web
    name: lineup
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: lineup-db
          property: connectionString
      - key: EMAIL_API_KEY
        sync: false
      - key: EMAIL_FROM
        value: noreply@togetherly.online
      - key: SITE_URL
        sync: false
    healthCheckPath: /

databases:
  - name: lineup-db
    plan: free
    databaseName: lineup
